import type { Metadata } from 'next'
import { Inter, Cinzel, Great_Vibes, Cormorant_Garamond } from 'next/font/google'
import './globals.css'

const cinzel = Cinzel({subsets: ['latin'], variable: '--font-cinzel'})
const greatVibes = Great_Vibes({ 
  weight: '400',
  subsets: ['latin'],
  variable: '--font-script', 
});
const cormorant = Cormorant_Garamond({ 
  weight: ['300', '400', '600'], // Traemos varios grosores para jugar con ellos
  subsets: ['latin'],
  variable: '--font-cormorant',
});


export const metadata: Metadata = {
  title: 'Invitacion Digital',
  description: 'Generated by NAVAX',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={` ${cinzel.variable} ${greatVibes.variable} ${cormorant.variable}`}>
      <body className= "font-serif antialiased text-stone-700 bg-rose-50/30">{children}</body>
    </html>
  )
}
